Valgrind merge from revision 10343 to 10837.  VEX IR merge from 1900 to 1913.

diff --git a/valgrind/docs/Makefile.am b/valgrind/docs/Makefile.am
--- a/valgrind/docs/Makefile.am
+++ b/valgrind/docs/Makefile.am
@@ -13,10 +13,62 @@ BUILD_ALL_DOCS=yes
 ## END OF HACK
 ##-------------------------------------------------------------
 
-
-SUBDIRS = xml lib images internals
-
-EXTRA_DIST = README
+EXTRA_DIST = \
+	README \
+	images/home.png \
+	images/next.png \
+	images/prev.png \
+	images/up.png \
+	internals/3_0_BUGSTATUS.txt \
+	internals/3_1_BUGSTATUS.txt \
+	internals/3_2_BUGSTATUS.txt \
+	internals/3_3_BUGSTATUS.txt \
+	internals/3_4_BUGSTATUS.txt \
+	internals/BIG_APP_NOTES.txt \
+	internals/Darwin-notes.txt \
+	internals/directory-structure.txt \
+	internals/howto_BUILD_KDE42.txt \
+	internals/howto_oprofile.txt \
+	internals/m_replacemalloc.txt \
+	internals/m_syswrap.txt \
+	internals/module-structure.txt \
+	internals/notes.txt \
+	internals/porting-HOWTO.txt \
+	internals/mpi2entries.txt \
+	internals/porting-to-ARM.txt \
+	internals/register-uses.txt \
+	internals/release-HOWTO.txt \
+	internals/segments-seginfos.txt \
+	internals/threads-syscalls-signals.txt \
+	internals/tm-mutexstates.dot \
+	internals/tm-threadstates.dot \
+	internals/tracking-fn-entry-exit.txt \
+	internals/why-no-libc.txt \
+	internals/xml-output.txt \
+	internals/xml-output-protocol4.txt \
+	lib/line-wrap.xsl \
+	lib/vg_basic.css \
+	lib/vg-fo.xsl \
+	lib/vg-faq2txt.xsl \
+	lib/vg-html-chunk.xsl \
+	lib/vg-html-website.xsl \
+	lib/vg-html-common.xsl \
+	xml/FAQ.xml \
+	xml/dist-docs.xml \
+	xml/index.xml \
+	xml/licenses.xml \
+	xml/manpages-index.xml \
+	xml/manual.xml \
+	xml/manual-intro.xml \
+	xml/manual-core.xml \
+	xml/manual-core-adv.xml \
+	xml/manual-writing-tools.xml \
+	xml/design-impl.xml \
+	xml/quick-start-guide.xml \
+	xml/tech-docs.xml \
+	xml/valgrind-manpage.xml \
+	xml/vg-entities.xml \
+	xml/xml_help.txt
 
 
 ##-------------------------------------------------------------------
@@ -55,9 +107,11 @@ XSL_HTML_CHUNK_STYLE  = $(mylibdir)/vg-html-chunk.xsl
 XSL_FO_STYLE          = $(mylibdir)/vg-fo.xsl
 XSL_TEXT_STYLE        = $(mylibdir)/vg-faq2txt.xsl
 XSL_WEBSITE_STYLE     = $(mylibdir)/vg-html-website.xsl
-XSL_MAN_STYLE = /usr/share/xml/docbook/stylesheet/nwalsh/current/manpages/docbook.xsl
+XSL_MAN_STYLES = \
+    /usr/share/xml/docbook/stylesheet/nwalsh/current/manpages/docbook.xsl \
+    /usr/share/xml/docbook/stylesheet/nwalsh/manpages/docbook.xsl
 
-all-docs: FAQ.txt man-page html-docs print-docs
+all-docs: FAQ.txt man-pages html-docs print-docs
 
 valid:
 	$(XMLLINT) $(XMLLINT_FLAGS) $(myxmldir)/index.xml
@@ -68,16 +122,21 @@ FAQ.txt:
 	export XML_CATALOG_FILES=$(XML_CATALOG_FILES) && \
 	$(XSLTPROC) $(XSLTPROC_FLAGS) -o ./FAQ.txt $(XSL_TEXT_STYLE) $(myxmldir)/FAQ.xml
 
-# the valgrind manpage
-man-page:
-	if test ! -f $(XSL_MAN_STYLE); then \
-	    echo "Error: I can't find the file '$(XSL_MAN_STYLE)'";     \
-	    echo "Please check where it lives on your system, and"      \
-	         "amend the line 'XSL_MAN_STYLE = ' in this Makefile."; \
-		  exit 1; \
-	fi;
-	export XML_CATALOG_FILES=$(XML_CATALOG_FILES) && \
-	$(XSLTPROC) $(XSLTPROC_FLAGS) -o ./ $(XSL_MAN_STYLE) $(myxmldir)/valgrind-manpage.xml
+# the valgrind manpages
+man-pages:
+	for x in $(XSL_MAN_STYLES) ; do \
+	    if test -f $$x; then \
+		echo "Using manpage stylesheet: $$x"; \
+		export XML_CATALOG_FILES=$(XML_CATALOG_FILES) && \
+		$(XSLTPROC) $(XSLTPROC_FLAGS) -o ./ $$x $(myxmldir)/manpages-index.xml; \
+		exit 0; \
+	    fi; \
+	done; \
+	echo ""; \
+	echo "Error: I can't find the XSL_MAN_STYLE file";     \
+	echo "Please check where it lives on your system, and"      \
+	     "amend the line 'XSL_MAN_STYLES = ' in this Makefile."; \
+	exit 1;
 
 # chunked html, on a chapter-by-chapter basis
 html-docs:
@@ -97,7 +156,6 @@ print-docs:
 	export XML_CATALOG_FILES=$(XML_CATALOG_FILES) && \
 	mkdir -p $(myprintdir) && \
 	mkdir -p $(myprintdir)/images && \
-	cp $(myimgdir)/massif-graph-sm.png $(myprintdir)/images && \
 	$(XSLTPROC) $(XSLTPROC_FLAGS) -o $(myprintdir)/index.fo $(XSL_FO_STYLE) $(myxmldir)/index.xml && \
 	(cd $(myprintdir) && \
          ( pdfxmltex index.fo && \
@@ -121,6 +179,12 @@ install-data-hook:
 		mkdir -p $(DESTDIR)$(datadir)/doc/valgrind; \
 		cp -r html $(DESTDIR)$(datadir)/doc/valgrind; \
 	fi
+	for f in *.1 ; do \
+		if test -r $$f ; then \
+			mkdir -p $(DESTDIR)$(mandir)/man1; \
+			cp $$f $(DESTDIR)$(mandir)/man1; \
+		fi \
+	done
  ifeq ($(BUILD_ALL_DOCS),yes)
 	if test -r index.pdf ; then \
 		mkdir -p $(DESTDIR)$(datadir)/doc/valgrind; \
@@ -130,31 +194,28 @@ install-data-hook:
 		mkdir -p $(DESTDIR)$(datadir)/doc/valgrind; \
 		cp index.ps $(DESTDIR)$(datadir)/doc/valgrind/valgrind_manual.ps; \
 	fi
-	if test -r valgrind.1 ; then \
-		mkdir -p $(DESTDIR)$(mandir)/man1; \
-		cp valgrind.1 $(DESTDIR)$(mandir)/man1/valgrind.1; \
-	fi
  endif
 
 # This is done at 'make dist' time.  It builds the html docs, print
-# docs and man page and copies them into the docs/ directory in the
+# docs and man pages and copies them into the docs/ directory in the
 # tarball.
  ifeq ($(BUILD_ALL_DOCS),yes)
-dist-hook: FAQ.txt html-docs print-docs man-page
+dist-hook: FAQ.txt html-docs man-pages print-docs
 	cp -r html $(distdir)
 	cp FAQ.txt $(distdir)/..
-	cp valgrind.1 $(distdir)
+	cp *.1 $(distdir)
 	cp print/index.pdf $(distdir)
 	cp print/index.ps $(distdir)
  else
-dist-hook: FAQ.txt html-docs man-page
-	cp FAQ.txt $(distdir)/..
+dist-hook: FAQ.txt html-docs man-pages
 	cp -r html $(distdir)
+	cp FAQ.txt $(distdir)/..
+	cp *.1 $(distdir)
  endif
 
 distclean-local:
 	rm -rf html print
-	rm -f $(top_builddir)/FAQ.txt
+	rm -f $(top_builddir)/FAQ.txt $(top_builddir)/docs/*.1
 
 
 
@@ -204,7 +265,6 @@ download-docs:
 	@echo "Generating valgrind_manual.pdf ..."
 	mkdir -p $(vgdir)/print
 	mkdir -p $(vgdir)/print/images
-	cp $(myimgdir)/massif-graph-sm.png $(vgdir)/print/images/
 	$(XSLTPROC) $(XSLTPROC_FLAGS) -o $(vgdir)/print/manual.fo $(XSL_FO_STYLE) $(myxmldir)/index.xml
 	(cd $(vgdir)/print/ && \
 		( pdfxmltex manual.fo && \
diff --git a/valgrind/docs/Makefile.in b/valgrind/docs/Makefile.in
--- a/valgrind/docs/Makefile.in
+++ b/valgrind/docs/Makefile.in
@@ -46,15 +46,6 @@ CONFIG_HEADER = $(top_builddir)/config.h
 CONFIG_CLEAN_FILES =
 SOURCES =
 DIST_SOURCES =
-RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
-	html-recursive info-recursive install-data-recursive \
-	install-exec-recursive install-info-recursive \
-	install-recursive installcheck-recursive installdirs-recursive \
-	pdf-recursive ps-recursive uninstall-info-recursive \
-	uninstall-recursive
-ETAGS = etags
-CTAGS = ctags
-DIST_SUBDIRS = $(SUBDIRS)
 DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
 ACLOCAL = @ACLOCAL@
 AMDEP_FALSE = @AMDEP_FALSE@
@@ -90,7 +81,6 @@ DEFAULT_SUPP = @DEFAULT_SUPP@
 DEFS = @DEFS@
 DEPDIR = @DEPDIR@
 DIFF = @DIFF@
-DISTCHECK_CONFIGURE_FLAGS = @DISTCHECK_CONFIGURE_FLAGS@
 ECHO_C = @ECHO_C@
 ECHO_N = @ECHO_N@
 ECHO_T = @ECHO_T@
@@ -106,7 +96,9 @@ FLAG_MSSE = @FLAG_MSSE@
 FLAG_UNLIMITED_INLINE_UNIT_GROWTH = @FLAG_UNLIMITED_INLINE_UNIT_GROWTH@
 FLAG_WDECL_AFTER_STMT = @FLAG_WDECL_AFTER_STMT@
 FLAG_W_EXTRA = @FLAG_W_EXTRA@
+FLAG_W_NO_EMPTY_BODY = @FLAG_W_NO_EMPTY_BODY@
 FLAG_W_NO_FORMAT_ZERO_LENGTH = @FLAG_W_NO_FORMAT_ZERO_LENGTH@
+FLAG_W_NO_UNINITIALIZED = @FLAG_W_NO_UNINITIALIZED@
 GDB = @GDB@
 GLIBC_VERSION = @GLIBC_VERSION@
 GREP = @GREP@
@@ -144,8 +136,6 @@ MAINTAINER_MODE_FALSE = @MAINTAINER_MODE_FALSE@
 MAINTAINER_MODE_TRUE = @MAINTAINER_MODE_TRUE@
 MAKEINFO = @MAKEINFO@
 MPI_CC = @MPI_CC@
-OBJC = @OBJC@
-OBJCFLAGS = @OBJCFLAGS@
 OBJEXT = @OBJEXT@
 PACKAGE = @PACKAGE@
 PACKAGE_BUGREPORT = @PACKAGE_BUGREPORT@
@@ -165,7 +155,6 @@ SHELL = @SHELL@
 STRIP = @STRIP@
 VALT_LOAD_ADDRESS = @VALT_LOAD_ADDRESS@
 VERSION = @VERSION@
-VEX_DIR = @VEX_DIR@
 VGCONF_ARCHS_INCLUDE_AMD64_FALSE = @VGCONF_ARCHS_INCLUDE_AMD64_FALSE@
 VGCONF_ARCHS_INCLUDE_AMD64_TRUE = @VGCONF_ARCHS_INCLUDE_AMD64_TRUE@
 VGCONF_ARCHS_INCLUDE_PPC32_FALSE = @VGCONF_ARCHS_INCLUDE_PPC32_FALSE@
@@ -205,7 +194,6 @@ VGCONF_PLATFORM_PRI_CAPS = @VGCONF_PLATFORM_PRI_CAPS@
 VGCONF_PLATFORM_SEC_CAPS = @VGCONF_PLATFORM_SEC_CAPS@
 ac_ct_CC = @ac_ct_CC@
 ac_ct_CXX = @ac_ct_CXX@
-ac_ct_OBJC = @ac_ct_OBJC@
 am__fastdepCC_FALSE = @am__fastdepCC_FALSE@
 am__fastdepCC_TRUE = @am__fastdepCC_TRUE@
 am__fastdepCXX_FALSE = @am__fastdepCXX_FALSE@
@@ -255,8 +243,63 @@ target_alias = @target_alias@
 # is not to skip building print docs.  Note, after changing it
 # you of course need to re-run configure to make it take effect.
 BUILD_ALL_DOCS = yes
-SUBDIRS = xml lib images internals
-EXTRA_DIST = README
+EXTRA_DIST = \
+	README \
+	images/home.png \
+	images/next.png \
+	images/prev.png \
+	images/up.png \
+	internals/3_0_BUGSTATUS.txt \
+	internals/3_1_BUGSTATUS.txt \
+	internals/3_2_BUGSTATUS.txt \
+	internals/3_3_BUGSTATUS.txt \
+	internals/3_4_BUGSTATUS.txt \
+	internals/BIG_APP_NOTES.txt \
+	internals/Darwin-notes.txt \
+	internals/directory-structure.txt \
+	internals/howto_BUILD_KDE42.txt \
+	internals/howto_oprofile.txt \
+	internals/m_replacemalloc.txt \
+	internals/m_syswrap.txt \
+	internals/module-structure.txt \
+	internals/notes.txt \
+	internals/porting-HOWTO.txt \
+	internals/mpi2entries.txt \
+	internals/porting-to-ARM.txt \
+	internals/register-uses.txt \
+	internals/release-HOWTO.txt \
+	internals/segments-seginfos.txt \
+	internals/threads-syscalls-signals.txt \
+	internals/tm-mutexstates.dot \
+	internals/tm-threadstates.dot \
+	internals/tracking-fn-entry-exit.txt \
+	internals/why-no-libc.txt \
+	internals/xml-output.txt \
+	internals/xml-output-protocol4.txt \
+	lib/line-wrap.xsl \
+	lib/vg_basic.css \
+	lib/vg-fo.xsl \
+	lib/vg-faq2txt.xsl \
+	lib/vg-html-chunk.xsl \
+	lib/vg-html-website.xsl \
+	lib/vg-html-common.xsl \
+	xml/FAQ.xml \
+	xml/dist-docs.xml \
+	xml/index.xml \
+	xml/licenses.xml \
+	xml/manpages-index.xml \
+	xml/manual.xml \
+	xml/manual-intro.xml \
+	xml/manual-core.xml \
+	xml/manual-core-adv.xml \
+	xml/manual-writing-tools.xml \
+	xml/design-impl.xml \
+	xml/quick-start-guide.xml \
+	xml/tech-docs.xml \
+	xml/valgrind-manpage.xml \
+	xml/vg-entities.xml \
+	xml/xml_help.txt
+
 myxmldir = $(top_srcdir)/docs/xml
 myimgdir = $(top_srcdir)/docs/images
 mylibdir = $(top_srcdir)/docs/lib
@@ -287,8 +330,11 @@ XSL_HTML_CHUNK_STYLE = $(mylibdir)/vg-html-chunk.xsl
 XSL_FO_STYLE = $(mylibdir)/vg-fo.xsl
 XSL_TEXT_STYLE = $(mylibdir)/vg-faq2txt.xsl
 XSL_WEBSITE_STYLE = $(mylibdir)/vg-html-website.xsl
-XSL_MAN_STYLE = /usr/share/xml/docbook/stylesheet/nwalsh/current/manpages/docbook.xsl
-all: all-recursive
+XSL_MAN_STYLES = \
+    /usr/share/xml/docbook/stylesheet/nwalsh/current/manpages/docbook.xsl \
+    /usr/share/xml/docbook/stylesheet/nwalsh/manpages/docbook.xsl
+
+all: all-am
 
 .SUFFIXES:
 $(srcdir)/Makefile.in: @MAINTAINER_MODE_TRUE@ $(srcdir)/Makefile.am  $(am__configure_deps)
@@ -321,140 +367,15 @@ $(top_srcdir)/configure: @MAINTAINER_MODE_TRUE@ $(am__configure_deps)
 $(ACLOCAL_M4): @MAINTAINER_MODE_TRUE@ $(am__aclocal_m4_deps)
 	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
 uninstall-info-am:
-
-# This directory's subdirectories are mostly independent; you can cd
-# into them and run `make' without going through this Makefile.
-# To change the values of `make' variables: instead of editing Makefiles,
-# (1) if the variable is set in `config.status', edit `config.status'
-#     (which will cause the Makefiles to be regenerated when you run `make');
-# (2) otherwise, pass the desired values on the `make' command line.
-$(RECURSIVE_TARGETS):
-	@failcom='exit 1'; \
-	for f in x $$MAKEFLAGS; do \
-	  case $$f in \
-	    *=* | --[!k]*);; \
-	    *k*) failcom='fail=yes';; \
-	  esac; \
-	done; \
-	dot_seen=no; \
-	target=`echo $@ | sed s/-recursive//`; \
-	list='$(SUBDIRS)'; for subdir in $$list; do \
-	  echo "Making $$target in $$subdir"; \
-	  if test "$$subdir" = "."; then \
-	    dot_seen=yes; \
-	    local_target="$$target-am"; \
-	  else \
-	    local_target="$$target"; \
-	  fi; \
-	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
-	  || eval $$failcom; \
-	done; \
-	if test "$$dot_seen" = "no"; then \
-	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
-	fi; test -z "$$fail"
-
-mostlyclean-recursive clean-recursive distclean-recursive \
-maintainer-clean-recursive:
-	@failcom='exit 1'; \
-	for f in x $$MAKEFLAGS; do \
-	  case $$f in \
-	    *=* | --[!k]*);; \
-	    *k*) failcom='fail=yes';; \
-	  esac; \
-	done; \
-	dot_seen=no; \
-	case "$@" in \
-	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
-	  *) list='$(SUBDIRS)' ;; \
-	esac; \
-	rev=''; for subdir in $$list; do \
-	  if test "$$subdir" = "."; then :; else \
-	    rev="$$subdir $$rev"; \
-	  fi; \
-	done; \
-	rev="$$rev ."; \
-	target=`echo $@ | sed s/-recursive//`; \
-	for subdir in $$rev; do \
-	  echo "Making $$target in $$subdir"; \
-	  if test "$$subdir" = "."; then \
-	    local_target="$$target-am"; \
-	  else \
-	    local_target="$$target"; \
-	  fi; \
-	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
-	  || eval $$failcom; \
-	done && test -z "$$fail"
-tags-recursive:
-	list='$(SUBDIRS)'; for subdir in $$list; do \
-	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
-	done
-ctags-recursive:
-	list='$(SUBDIRS)'; for subdir in $$list; do \
-	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
-	done
-
-ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
-	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
-	unique=`for i in $$list; do \
-	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
-	  done | \
-	  $(AWK) '    { files[$$0] = 1; } \
-	       END { for (i in files) print i; }'`; \
-	mkid -fID $$unique
 tags: TAGS
+TAGS:
 
-TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
-		$(TAGS_FILES) $(LISP)
-	tags=; \
-	here=`pwd`; \
-	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
-	  include_option=--etags-include; \
-	  empty_fix=.; \
-	else \
-	  include_option=--include; \
-	  empty_fix=; \
-	fi; \
-	list='$(SUBDIRS)'; for subdir in $$list; do \
-	  if test "$$subdir" = .; then :; else \
-	    test ! -f $$subdir/TAGS || \
-	      tags="$$tags $$include_option=$$here/$$subdir/TAGS"; \
-	  fi; \
-	done; \
-	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
-	unique=`for i in $$list; do \
-	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
-	  done | \
-	  $(AWK) '    { files[$$0] = 1; } \
-	       END { for (i in files) print i; }'`; \
-	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
-	  test -n "$$unique" || unique=$$empty_fix; \
-	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
-	    $$tags $$unique; \
-	fi
 ctags: CTAGS
-CTAGS: ctags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
-		$(TAGS_FILES) $(LISP)
-	tags=; \
-	here=`pwd`; \
-	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
-	unique=`for i in $$list; do \
-	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
-	  done | \
-	  $(AWK) '    { files[$$0] = 1; } \
-	       END { for (i in files) print i; }'`; \
-	test -z "$(CTAGS_ARGS)$$tags$$unique" \
-	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
-	     $$tags $$unique
+CTAGS:
 
-GTAGS:
-	here=`$(am__cd) $(top_builddir) && pwd` \
-	  && cd $(top_srcdir) \
-	  && gtags -i $(GTAGS_ARGS) $$here
-
-distclean-tags:
-	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
 
 distdir: $(DISTFILES)
+	$(mkdir_p) $(distdir)/images $(distdir)/internals $(distdir)/lib $(distdir)/xml
 	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
 	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
 	list='$(DISTFILES)'; for file in $$list; do \
@@ -481,38 +402,22 @@ distdir: $(DISTFILES)
 	    || exit 1; \
 	  fi; \
 	done
-	list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
-	  if test "$$subdir" = .; then :; else \
-	    test -d "$(distdir)/$$subdir" \
-	    || $(mkdir_p) "$(distdir)/$$subdir" \
-	    || exit 1; \
-	    distdir=`$(am__cd) $(distdir) && pwd`; \
-	    top_distdir=`$(am__cd) $(top_distdir) && pwd`; \
-	    (cd $$subdir && \
-	      $(MAKE) $(AM_MAKEFLAGS) \
-	        top_distdir="$$top_distdir" \
-	        distdir="$$distdir/$$subdir" \
-	        distdir) \
-	      || exit 1; \
-	  fi; \
-	done
 	$(MAKE) $(AM_MAKEFLAGS) \
 	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
 	  dist-hook
 check-am: all-am
-check: check-recursive
+check: check-am
 all-am: Makefile
-installdirs: installdirs-recursive
-installdirs-am:
-install: install-recursive
-install-exec: install-exec-recursive
-install-data: install-data-recursive
-uninstall: uninstall-recursive
+installdirs:
+install: install-am
+install-exec: install-exec-am
+install-data: install-data-am
+uninstall: uninstall-am
 
 install-am: all-am
 	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
 
-installcheck: installcheck-recursive
+installcheck: installcheck-am
 install-strip:
 	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
 	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
@@ -528,22 +433,21 @@ distclean-generic:
 maintainer-clean-generic:
 	@echo "This command is intended for maintainers to use"
 	@echo "it deletes files that may require special tools to rebuild."
-clean: clean-recursive
+clean: clean-am
 
 clean-am: clean-generic mostlyclean-am
 
-distclean: distclean-recursive
+distclean: distclean-am
 	-rm -f Makefile
-distclean-am: clean-am distclean-generic distclean-local \
-	distclean-tags
+distclean-am: clean-am distclean-generic distclean-local
 
-dvi: dvi-recursive
+dvi: dvi-am
 
 dvi-am:
 
-html: html-recursive
+html: html-am
 
-info: info-recursive
+info: info-am
 
 info-am:
 
@@ -553,47 +457,41 @@ install-data-am:
 
 install-exec-am:
 
-install-info: install-info-recursive
+install-info: install-info-am
 
 install-man:
 
 installcheck-am:
 
-maintainer-clean: maintainer-clean-recursive
+maintainer-clean: maintainer-clean-am
 	-rm -f Makefile
 maintainer-clean-am: distclean-am maintainer-clean-generic
 
-mostlyclean: mostlyclean-recursive
+mostlyclean: mostlyclean-am
 
 mostlyclean-am: mostlyclean-generic
 
-pdf: pdf-recursive
+pdf: pdf-am
 
 pdf-am:
 
-ps: ps-recursive
+ps: ps-am
 
 ps-am:
 
 uninstall-am: uninstall-info-am
 
-uninstall-info: uninstall-info-recursive
-
-.PHONY: $(RECURSIVE_TARGETS) CTAGS GTAGS all all-am check check-am \
-	clean clean-generic clean-recursive ctags ctags-recursive \
-	dist-hook distclean distclean-generic distclean-local \
-	distclean-recursive distclean-tags distdir dvi dvi-am html \
-	html-am info info-am install install-am install-data \
+.PHONY: all all-am check check-am clean clean-generic dist-hook \
+	distclean distclean-generic distclean-local distdir dvi dvi-am \
+	html html-am info info-am install install-am install-data \
 	install-data-am install-data-hook install-exec install-exec-am \
 	install-info install-info-am install-man install-strip \
-	installcheck installcheck-am installdirs installdirs-am \
-	maintainer-clean maintainer-clean-generic \
-	maintainer-clean-recursive mostlyclean mostlyclean-generic \
-	mostlyclean-recursive pdf pdf-am ps ps-am tags tags-recursive \
-	uninstall uninstall-am uninstall-info-am
+	installcheck installcheck-am installdirs maintainer-clean \
+	maintainer-clean-generic mostlyclean mostlyclean-generic pdf \
+	pdf-am ps ps-am uninstall uninstall-am uninstall-info-am
 
 
-all-docs: FAQ.txt man-page html-docs print-docs
+all-docs: FAQ.txt man-pages html-docs print-docs
 
 valid:
 	$(XMLLINT) $(XMLLINT_FLAGS) $(myxmldir)/index.xml
@@ -604,16 +502,21 @@ FAQ.txt:
 	export XML_CATALOG_FILES=$(XML_CATALOG_FILES) && \
 	$(XSLTPROC) $(XSLTPROC_FLAGS) -o ./FAQ.txt $(XSL_TEXT_STYLE) $(myxmldir)/FAQ.xml
 
-# the valgrind manpage
-man-page:
-	if test ! -f $(XSL_MAN_STYLE); then \
-	    echo "Error: I can't find the file '$(XSL_MAN_STYLE)'";     \
-	    echo "Please check where it lives on your system, and"      \
-	         "amend the line 'XSL_MAN_STYLE = ' in this Makefile."; \
-		  exit 1; \
-	fi;
-	export XML_CATALOG_FILES=$(XML_CATALOG_FILES) && \
-	$(XSLTPROC) $(XSLTPROC_FLAGS) -o ./ $(XSL_MAN_STYLE) $(myxmldir)/valgrind-manpage.xml
+# the valgrind manpages
+man-pages:
+	for x in $(XSL_MAN_STYLES) ; do \
+	    if test -f $$x; then \
+		echo "Using manpage stylesheet: $$x"; \
+		export XML_CATALOG_FILES=$(XML_CATALOG_FILES) && \
+		$(XSLTPROC) $(XSLTPROC_FLAGS) -o ./ $$x $(myxmldir)/manpages-index.xml; \
+		exit 0; \
+	    fi; \
+	done; \
+	echo ""; \
+	echo "Error: I can't find the XSL_MAN_STYLE file";     \
+	echo "Please check where it lives on your system, and"      \
+	     "amend the line 'XSL_MAN_STYLES = ' in this Makefile."; \
+	exit 1;
 
 # chunked html, on a chapter-by-chapter basis
 html-docs:
@@ -633,7 +536,6 @@ print-docs:
 	export XML_CATALOG_FILES=$(XML_CATALOG_FILES) && \
 	mkdir -p $(myprintdir) && \
 	mkdir -p $(myprintdir)/images && \
-	cp $(myimgdir)/massif-graph-sm.png $(myprintdir)/images && \
 	$(XSLTPROC) $(XSLTPROC_FLAGS) -o $(myprintdir)/index.fo $(XSL_FO_STYLE) $(myxmldir)/index.xml && \
 	(cd $(myprintdir) && \
          ( pdfxmltex index.fo && \
@@ -657,6 +559,12 @@ install-data-hook:
 		mkdir -p $(DESTDIR)$(datadir)/doc/valgrind; \
 		cp -r html $(DESTDIR)$(datadir)/doc/valgrind; \
 	fi
+	for f in *.1 ; do \
+		if test -r $$f ; then \
+			mkdir -p $(DESTDIR)$(mandir)/man1; \
+			cp $$f $(DESTDIR)$(mandir)/man1; \
+		fi \
+	done
  ifeq ($(BUILD_ALL_DOCS),yes)
 	if test -r index.pdf ; then \
 		mkdir -p $(DESTDIR)$(datadir)/doc/valgrind; \
@@ -666,31 +574,28 @@ install-data-hook:
 		mkdir -p $(DESTDIR)$(datadir)/doc/valgrind; \
 		cp index.ps $(DESTDIR)$(datadir)/doc/valgrind/valgrind_manual.ps; \
 	fi
-	if test -r valgrind.1 ; then \
-		mkdir -p $(DESTDIR)$(mandir)/man1; \
-		cp valgrind.1 $(DESTDIR)$(mandir)/man1/valgrind.1; \
-	fi
  endif
 
 # This is done at 'make dist' time.  It builds the html docs, print
-# docs and man page and copies them into the docs/ directory in the
+# docs and man pages and copies them into the docs/ directory in the
 # tarball.
  ifeq ($(BUILD_ALL_DOCS),yes)
-dist-hook: FAQ.txt html-docs print-docs man-page
+dist-hook: FAQ.txt html-docs man-pages print-docs
 	cp -r html $(distdir)
 	cp FAQ.txt $(distdir)/..
-	cp valgrind.1 $(distdir)
+	cp *.1 $(distdir)
 	cp print/index.pdf $(distdir)
 	cp print/index.ps $(distdir)
  else
-dist-hook: FAQ.txt html-docs man-page
-	cp FAQ.txt $(distdir)/..
+dist-hook: FAQ.txt html-docs man-pages
 	cp -r html $(distdir)
+	cp FAQ.txt $(distdir)/..
+	cp *.1 $(distdir)
  endif
 
 distclean-local:
 	rm -rf html print
-	rm -f $(top_builddir)/FAQ.txt
+	rm -f $(top_builddir)/FAQ.txt $(top_builddir)/docs/*.1
 
 # -----------------------------------------------------------------------
 # Note: the rest of this file is nothing to do with the normal build
@@ -738,7 +643,6 @@ download-docs:
 	@echo "Generating valgrind_manual.pdf ..."
 	mkdir -p $(vgdir)/print
 	mkdir -p $(vgdir)/print/images
-	cp $(myimgdir)/massif-graph-sm.png $(vgdir)/print/images/
 	$(XSLTPROC) $(XSLTPROC_FLAGS) -o $(vgdir)/print/manual.fo $(XSL_FO_STYLE) $(myxmldir)/index.xml
 	(cd $(vgdir)/print/ && \
 		( pdfxmltex manual.fo && \
